name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:

    staging:
      materialized: view

    marts:
      materialized: table

    quality:
      materialized: table

    sources:
      enabled: true

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_project', 'dbt_utils']
