name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:

    staging:
      materialized: view  # staging models are usually lightweight and rebuilt often

    marts:
      materialized: table  # final models used for reporting or consumption

    quality:
      materialized: table  # helpful to persist data validation results

    sources:
      enabled: true  # only holds .yml source definitions

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_project', 'dbt_utils']
